### ISSUE TITLE
Support for bevy 0.13.2

### ISSUE THREAD

**Issue by scorsi** [makspll/bevy_mod_scripting#116]
Hello,

I would like to use bevy `0.13.2`, is there a reason why bevy is hard-locked to `0.13.1` ?

Thanks,

**Comment by makspll** [comment]
Hey, yes mainly the way we generate code right now. The version built for 0.13.1 had codegen for 0.13.1 but NOT for 0.13.2. I am not sure if there are real issues that could come out of codegen not being up to date to a patch version. But I wanted to be safe and avoid this sort of thing. If this is too annoying I am happy to re-consider

**Comment by scorsi** [comment]
I see, you're right, I hadn't thought of that.
