### ISSUE TITLE
Indexing the `Children` component always yields `nil`

### ISSUE THREAD

**Issue by Joakker** [makspll/bevy_mod_scripting#121]
In a script like the following

```lua
function Example()
    local children_t = world:get_type_by_name 'Children'
    local children = world:get_component(entity, children_t)

    print(chilren) -- Prints `Children([...])`

    print(children[1]) -- Prints `nil`
end
```

Even if the `Children` component is not empty, trying to get the nth child via the proxy reference always yields nil instead

**Comment by makspll** [comment]
This is because Children is a component containing a private smallvec, indexing into the component itself is not a defined operation, the current wrapper does not define an index or new index metamethod (none of the wrappers apart from glam types do)

**Comment by makspll** [comment]
However, the world userdata does define get_children and similar functions

**Comment by Joakker** [comment]
Thank you
