### ISSUE TITLE
Publish 0.7?

### ISSUE THREAD

**Issue by shanecelis** [makspll/bevy_mod_scripting#132]
Thank you for supporting bevy 0.14 on main! It's been working wonderfully. I've been using it without issue for some time now. Perhaps it's time to push a release to crates.io. Is there anything that's blocking that you need help with?

**Comment by makspll** [comment]
I've been procrastinating building proper CD pipelines, the reason I haven't released in a while is it's a massive chore. I've just integrated release-plz which looks really cool and should make this a breeze :D

**Comment by shanecelis** [comment]
You rock!

**Comment by shanecelis** [comment]
I added [an announcement post](https://discord.com/channels/691052431525675048/918591326096850974/1305668650862252094) to the bevy discord for the release.
