### ISSUE TITLE
Dynamic queries

### ISSUE THREAD

**Issue by makspll** [makspll/bevy_mod_scripting#20]
Allow scripts querying for entities with different components.
- [ ] Write (Owned only) Lua wrappers around `bevy_ecs_dynamic`
- [ ] Add them to the APIProvider

**Comment by makspll** [comment]
This would benefit from:
https://github.com/jakobhellermann/bevy_mod_js_scripting/issues/5

**Comment by JoeHowarth** [comment]
Any guidance on how to get started implementing this?

**Comment by makspll** [comment]
@JoeHowarth Sorry for delay, I want to give you an in-depth answer but just don't have the time to delve into this. I'll come back to you at some point! 

In the meantime however, essentially you'd be changing the `ReflectionPath` structures, to contain whatever you need to work with `bevy_ecs_dynamic` and also all the code which uses their constructors which might be quite a few places
