### ISSUE TITLE
Bevy v0.9 Support

### ISSUE THREAD

**Issue by chrisburnor** [makspll/bevy_mod_scripting#39]
This crate should be updated to support Bevy v0.9

**Comment by makspll** [comment]
Indeed, work is currently under way over at https://github.com/makspll/bevy_mod_scripting/pull/38, attempting to sort everything out as we speak

**Comment by chrisburnor** [comment]
We can close this as dupe. I completely missed that ticket.

**Comment by makspll** [comment]
Oh no don't worry, that's a PR without a corresponding ticket
