### ISSUE TITLE
console_integration outdate

### ISSUE THREAD

**Issue by Lightnet** [makspll/bevy_mod_scripting#42]
The example file for console integration seem out date. I can get part of it working. There not much example of set up the Cargo.toml.

Try work on windows.
```
[dependencies]
bevy = "0.9"
clap = "4.0.32"
bevy_console = "0.6.0"
bevy_mod_scripting = {version = "0.2.2", features =["lua","lua54"]}
```

Found the bevy_console has change some set up.

```
#[derive(Parser, ConsoleCommand)]
#[command(name = "run_script")]
```

```
//  no method named `get_world` found for reference `&bevy_mod_scripting::prelude::Lua` in the current scope
let world = ctx.get_world()?
//method not found in `&bevy_mod_scripting::prelude::Lua`
```

```
//mismatched types
events.send(PrintConsoleLine { line: msg });
//expected struct `clap::builder::StyledStr`, found struct `std::string::String`
```

There are some area can't figure since wanted to keep it simple. Still learning how to get part example working. Not sure how to config them right.

**Comment by makspll** [comment]
Hi @Lightnet! Thanks for opening the issue!

Which command are you running exactly? If I clone the repo and run:
`cargo run --example console_integration_lua --features=lua54,lua_script_api` the example seems to work fine.

I can see you've pasted a part of some `Cargo.toml` file, in the file you're using the `0.6.0` version of bevy_console whereas the example uses `0.5.0`

**Comment by Lightnet** [comment]
That help. I was not sure of the config setup for Cargo.toml.

**Comment by makspll** [comment]
Glad to hear, feel free to ask if you have any other issues!
