### ISSUE TITLE
Compile error caused by `tealr_derive`

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [makspll/bevy_mod_scripting#60]
Trying to build [this project](https://github.com/JohnTheCoolingFan/scriplets/tree/experiments) causes a compile error: https://gist.github.com/JohnTheCoolingFan/3e4ae02a70dcd94d6925dbdc73e4832e

Filed an issue at `tealr` repo as well: https://github.com/lenscas/tealr/issues/80

**Comment by makspll** [comment]
are you running the newest version of rust ? `rustup update` if not

**Comment by JohnTheCoolingFan** [comment]
Yes, I am using latest stable rust 1.70.

I will try to update packages on my arch install later, mayeb that changes something...

**Comment by makspll** [comment]
Hmm I see, do keep us updated, I will try investigate at some point

**Comment by JohnTheCoolingFan** [comment]
No, updating my packages didn't fix teh issue. I'll ask for help on rust community discord.

**Comment by saethlin** [comment]
This is probably a compiler bug, see https://github.com/rust-lang/rust/issues/111888#issuecomment-1585690896

(you would be justified in closing this issue)
