### ISSUE TITLE
Rhai Events are overriding each other

### ISSUE THREAD

**Issue by zwazel** [makspll/bevy_mod_scripting#75]
Hi!
Could be that I completely misunderstand events in this crate.
I've implemented a function that allows me to spawn a mod.
So via script, i can just spawn other mods.
and those spawned mods then get called the "on_init" function in their script!

problem is, as soon as there is more than just one at the same time, only one of them gets the init method called.

same thing for the Update call.
I can't use Recipients::All because i need to do some additional checks before calling on_update on that entity, so i use Recipient::Entity, and loop through all of them. and here the same problem!

~~Am I misunderstanding something or is this a "design flaw"?~~
Noticed that this is a bug in the rhai implementation. Lua did not behave Like this.

**Comment by makspll** [comment]
Hi @zwazel fantastic catch! That's indeed a bug, the rhai implementation was not aligned with the Lua one here, thanks a lot for the PR! Please fire any more issues this way, I think not that many people have used the Rhai side of this crate so there might well be some more bumps along the way!

**Comment by zwazel** [comment]
glad i could help, and that's exactly what i'll do as i'm working quite a lot with rhai right now :)
