### ISSUE TITLE
Bevy 0.12

### ISSUE THREAD

**Issue by chipsenkbeil** [makspll/bevy_mod_scripting#88]
I saw #62 for bevy 0.11 support, and it looks like [bevy 0.12](https://github.com/bevyengine/bevy/releases/tag/v0.12.0) was released a couple of weeks ago. I'm starting a new project where I'll lock into a certain version of bevy.

Given the last release in May covered bevy 0.10, should I leverage bevy 0.11 or bevy 0.12 in anticipation for the next release of this crate? I'm brand new, so I don't (and shouldn't) have much weight in the decision here. Just want to know if there are plans/expectations for one version over the other! 😄 

I'd toss this into a discussion instead of an issue, but looks like discussions aren't enabled for this repository. So apologies if this clutters the issue section!

**Comment by makspll** [comment]
Hey and welcome!

I am anticipating 2 releases very soon, same feature set, 2 latest bevy versions, hopefully within a week or two.

Hope that helps :)

**Comment by chipsenkbeil** [comment]
It does! Thank you for the lightning fast response 😄 Going to close this out since you've answered my question!
