### ISSUE TITLE
Better CI

### ISSUE THREAD

**Issue by makspll** [makspll/bevy_mod_scripting#9]
Current CI is extremely slow

**Comment by coderedart** [comment]
was wondering if it is possible to disable default features for bevy and only include the features that the `event_priority` and `mod_scripting` crates actually use. 

there's a security advisory about `stdweb` (unmaintained) and `time` (seg fault possible) crates which are dependencies of `bevy_gilrs`. this was making my `Cargo Checkmate` workflow fail and i spent an hour trying to find out why `bevy_gilrs` was getting included in my `Cargo.lock` file xD.

**Comment by makspll** [comment]
Haha, yeah for now I've everything from bevy included to avoid dev-hassle, but closer to the release (very soon) I will go through and make sure not everything is included.

Having said that, once the general API hits, that will touch most bevy crates (although I doubt it will touch bevy_gilrs)
